version: "3.9"
networks:
  data:
    external:
      name: waisy

x-kafka-common:
  &kafka-common
  image: waisy/kafka:2.8.1-2.13
  networks:
      - data
  volumes:
    - ./kafka/config/server.properties:/kafka/config/server.properties
  depends_on:
    - zookeeper
  restart: always

services:
  zookeeper:
    image: zookeeper:3.5.9
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - data
    ports:
      - "2181:2181"
      - "8080:8080"
    volumes:
      - ./conf/zoo.cfg:/conf/zoo.cfg
      - ~/data/zookeeper/zk1/data:/data

  kafka:
    <<: *kafka-common
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      MODE: 'server'

  cmak:
    container_name: cmak
    hostname: cmak
    image: waisy/cmak:3.0.0.5-v1
    networks:
      - data
    ports:
      - "9000:9000"
    volumes:
      - ./cmak/conf/application.conf:/etc/cmak/application.conf
    environment:
      ZK_HOSTS: 'zookeeper:2181'
    restart: always

  # zoo-navi:
  #   image: elkozmon/zoonavigator
  #   container_name: navi
  #   hostname: navi
  #   # networks:
  #   #   - data
  #   ports:
  #     - 9001:9000
  #   environment:
  #     HTTP_PORT: 9000